name: Gitee repos mirror periodic job

on:
  workflow_dispatch:
  #pull_request:
    # Runs at every pull requests submitted in master branch 
    #branches: [ main ]
  schedule:
   
    - cron:  '0 */2 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Mirror the Github organization repos to Gitee.
      uses: Yikun/hub-mirror-action@v1.3
      with:
        src: github/truecharts
        dst: gitee/truecharts
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token:  ${{ secrets.GITEE_TOKEN }}
        
        timeout: 600
        debug: true
        force_update: true
        white_list: "catalog,dh_catalog,library-charts"
    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        retain_days: 1
        keep_minimum_runs: 2
